//! First-run setup wizard: when no config file exists, the server boots a
//! minimal web form instead of the drive. The user pastes their Telegram app
//! credentials and phone number; the wizard validates them, generates the
//! session secret, writes `config.toml`, and exits — the operator then starts
//! ii-drive normally. Exiting (rather than hot-swapping the config) keeps
//! behavior identical on every platform and supervisor.

use axum::extract::State;
use axum::response::{Html, IntoResponse, Response};
use axum::{Json, Router};
use std::net::SocketAddr;
use std::path::{Path, PathBuf};

/// Runs when `config_path` does not exist. Serves the wizard until a valid
/// submission lands, writes the file, then returns — main() exits with a
/// "start again" message.
pub async fn run(config_path: PathBuf) -> anyhow::Result<()> {
    // The wizard binds loopback by default so credentials are never
    // submitted over an unauthenticated LAN hop.
    let cfg = crate::config::get();
    let addr: SocketAddr = format!("{}:{}", cfg.host, cfg.port)
        .parse()
        .map_err(|e| anyhow::anyhow!("invalid host/port from defaults: {e}"))?;

    let listener = tokio::net::TcpListener::bind(addr).await?;
    tracing::info!("no config found — setup wizard running on http://{addr}");

    let state = SetupState { config_path };
    let app = Router::new()
        .route("/", axum::routing::get(page))
        .route("/api/setup", axum::routing::post(submit))
        .with_state(state);
    axum::serve(listener, app).await?;
    Ok(())
}

#[derive(Clone)]
struct SetupState {
    config_path: PathBuf,
}

async fn page() -> Html<&'static str> {
    Html(PAGE)
}

#[derive(serde::Deserialize)]
struct SetupBody {
    api_id: i64,
    api_hash: String,
    /// One phone per line or comma-separated; both tolerated.
    phones: String,
}

async fn submit(State(state): State<SetupState>, Json(body): Json<SetupBody>) -> Response {
    match validate_and_write(&state.config_path, body) {
        Ok(msg) => {
            // Let the response reach the browser before exiting.
            tokio::spawn(async {
                tokio::time::sleep(std::time::Duration::from_millis(800)).await;
                std::process::exit(0);
            });
            ([(axum::http::header::CONTENT_TYPE, "text/html")], msg).into_response()
        }
        Err(e) => (axum::http::StatusCode::BAD_REQUEST, e).into_response(),
    }
}

fn normalize_phone(raw: &str) -> Option<String> {
    let digits: String = raw.chars().filter(|c| c.is_ascii_digit()).collect();
    (digits.len() >= 6 && digits.len() <= 15).then_some(digits)
}

fn validate_and_write(config_path: &Path, body: SetupBody) -> Result<String, String> {
    let api_hash = body.api_hash.trim().to_string();
    if api_hash.len() != 32 || !api_hash.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err("api_hash must be the 32-character hex string from my.telegram.org".into());
    }
    if body.api_id <= 0 {
        return Err("api_id must be a positive number from my.telegram.org".into());
    }

    let mut phones = Vec::new();
    for raw in body.phones.split([',', '\n', ';']) {
        if raw.trim().is_empty() {
            continue;
        }
        let normalized =
            normalize_phone(raw).ok_or_else(|| format!("`{raw}` is not a valid phone number"))?;
        phones.push(normalized);
    }
    if phones.is_empty() {
        return Err("at least one phone number is required".into());
    }

    // The secret is generated here rather than at next boot so the written
    // config is complete and restart-stable.
    let bytes: [u8; 32] = rand::random();
    let secret = hex::encode(bytes);

    let phones_toml = phones
        .iter()
        .map(|p| format!("    \"+{p}\","))
        .collect::<Vec<_>>()
        .join("\n");
    let toml = format!(
        r#"# Generated by the first-run setup wizard.
# See config.example.toml for every option.

api_id = {api_id}
api_hash = "{api_hash}"
secret = "{secret}"

allowed_phones = [
{phones_toml}
]

# The wizard's phone doubles as the operator (admin endpoints); edit to taste.
admin_phones = [
{phones_toml}
]
"#,
        api_id = body.api_id,
    );

    std::fs::write(config_path, toml)
        .map_err(|e| format!("could not write {}: {e}", config_path.display()))?;

    Ok(format!(
        "<html><body style=\"font-family:sans-serif;background:#0d1117;color:#e6edf3;\
         display:flex;align-items:center;justify-content:center;height:100vh;margin:0\">\
         <div style=\"text-align:center\"><h1>✓ Setup complete</h1>\
         <p>Configuration written to <code>{}</code>.</p>\
         <p>Start ii-drive again, then sign in.</p></div></body></html>",
        config_path.display()
    ))
}

const PAGE: &str = r##"<!doctype html>
<html><head><meta charset="utf-8"><title>ii-drive setup</title>
<style>
body{font-family:sans-serif;background:#0d1117;color:#e6edf3;display:flex;
align-items:center;justify-content:center;min-height:100vh;margin:0}
.card{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:28px;
width:min(480px,90vw)}
h1{margin-top:0;font-size:1.2rem}
label{display:block;margin:14px 0 4px;font-size:.85rem;color:#8b949e}
input{width:100%;box-sizing:border-box;padding:8px;border-radius:6px;
border:1px solid #30363d;background:#0d1117;color:#e6edf3}
button{margin-top:18px;width:100%;padding:10px;border:0;border-radius:6px;
background:#238636;color:white;font-size:1rem;cursor:pointer}
button:disabled{opacity:.6}
.hint{font-size:.75rem;color:#8b949e;margin-top:4px}
a{color:#58a6ff}
#msg{color:#f85149;margin-top:12px;font-size:.85rem;white-space:pre-wrap}
</style></head><body><div class="card">
<h1>Welcome to ii-drive</h1>
<p class="hint">First run: paste your Telegram app credentials. Create them at
<a href="https://my.telegram.org/apps" target="_blank">my.telegram.org/apps</a>
— takes two minutes.</p>
<label>api_id</label><input id="api_id" placeholder="1234567">
<label>api_hash</label><input id="api_hash" placeholder="32-character hex string">
<label>Your phone number(s)</label>
<input id="phones" placeholder="+15551234567">
<p class="hint">Comma-separate several. Only these numbers can sign in.</p>
<button id="go">Save &amp; finish</button>
<div id="msg"></div>
</div>
<script>
const b=document.getElementById('go');
b.onclick=async()=>{
 b.disabled=true;document.getElementById('msg').textContent='';
 try{
  const res=await fetch('/api/setup',{method:'POST',
   headers:{'Content-Type':'application/json'},
   body:JSON.stringify({api_id:+document.getElementById('api_id').value,
    api_hash:document.getElementById('api_hash').value.trim(),
    phones:document.getElementById('phones').value})});
  const t=await res.text();
  if(res.ok){document.querySelector('.card').innerHTML=t;}
  else{document.getElementById('msg').textContent=t;b.disabled=false;}
 }catch(e){document.getElementById('msg').textContent=e.message;b.disabled=false;}
};
</script></body></html>"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writes_complete_config() {
        let dir = std::env::temp_dir().join("iidrive-setup-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("config.toml");
        let _ = std::fs::remove_file(&path);

        let msg = validate_and_write(
            &path,
            SetupBody {
                api_id: 12345,
                api_hash: "a".repeat(32),
                phones: "+1 555 123 4567, +447700900123".into(),
            },
        )
        .unwrap();

        assert!(msg.contains("Setup complete"));
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("api_id = 12345"));
        assert!(text.contains("+15551234567"));
        assert!(text.contains("+447700900123"));
        // Secret is generated and never a known constant.
        let secret_line = text.lines().find(|l| l.starts_with("secret")).unwrap();
        assert!(!secret_line.contains("change-me"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn rejects_bad_credentials() {
        let dir = std::env::temp_dir().join("iidrive-setup-bad");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("config.toml");

        assert!(
            validate_and_write(
                &path,
                SetupBody {
                    api_id: 0,
                    api_hash: "a".repeat(32),
                    phones: "+15551234567".into()
                }
            )
            .is_err()
        );
        assert!(
            validate_and_write(
                &path,
                SetupBody {
                    api_id: 5,
                    api_hash: "short".into(),
                    phones: "+15551234567".into()
                }
            )
            .is_err()
        );
        assert!(
            validate_and_write(
                &path,
                SetupBody {
                    api_id: 5,
                    api_hash: "a".repeat(32),
                    phones: "abc".into()
                }
            )
            .is_err()
        );
        std::fs::remove_dir_all(&dir).ok();
    }
}
